version: "3.7"

services:
    zoo1:
        image: zookeeper:latest
        hostname: zoo1
        ports:
            - "2181:2181"
        environment:
            ZOO_MY_ID: 1
            ZOO_PORT: "2181"
        volumes:
            - ./zk-kafka/zoo1/data:/data
            - ./zk-kafka/zoo1/datalog:/datalog

    zoo2:
        image: zookeeper:latest
        hostname: zoo2
        ports:
            - "2182:2182"
        environment:
            ZOO_MY_ID: 2
            ZOO_PORT: "2182"
        volumes:
            - ./zk-kafka/zoo2/data:/data
            - ./zk-kafka/zoo2/datalog:/datalog

    kafka1:
        image: wurstmeister/kafka
        hostname: kafka1
        ports:
            - "9091:9091"
        expose: 
            - "29091"
        environment:
            KAFKA_LISTENERS: INSIDE://0.0.0.0:29091,OUTSIDE://0.0.0.0:9091
            KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka1:29091,OUTSIDE://localhost:9091
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
            KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181,zoo2:2182"
            KAFKA_BROKER_ID: 1
            KAFKA_LOG_DIRS: /var/lib/kafka/logs
            KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
        volumes:
            - ./zk-kafka/kafka1/data:/var/lib/kafka/data
            - ./zk-kafka/kafka1/logs:/var/lib/kafka/logs
        depends_on:
            - zoo1
            - zoo2

    kafka2:
        image: wurstmeister/kafka
        hostname: kafka2
        ports:
            - "9092:9092"
        expose: 
            - "29092"
        environment:
            KAFKA_LISTENERS: INSIDE://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
            KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka2:29092,OUTSIDE://localhost:9092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
            KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181,zoo2:2182"
            KAFKA_BROKER_ID: 2
            KAFKA_LOG_DIRS: /var/lib/kafka/logs
            KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
        volumes:
            - ./zk-kafka/kafka2/data:/var/lib/kafka/data
            - ./zk-kafka/kafka2/logs:/var/lib/kafka/logs
        depends_on:
            - zoo1
            - zoo2

    kafka3:
        image: wurstmeister/kafka
        hostname: kafka3
        ports:
            - "9093:9093"
        expose: 
            - "29093"
        environment:
            KAFKA_LISTENERS: INSIDE://0.0.0.0:29093,OUTSIDE://0.0.0.0:9093
            KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka3:29093,OUTSIDE://localhost:9093
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
            KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181,zoo2:2182"
            KAFKA_BROKER_ID: 3
            KAFKA_LOG_DIRS: /var/lib/kafka/logs
            KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
        volumes:
            - ./zk-kafka/kafka3/data:/var/lib/kafka/data
            - ./zk-kafka/kafka3/logs:/var/lib/kafka/logs
        depends_on:
            - zoo1
            - zoo2